import chess
board = chess.Board()
# Making moves using Standard Algebraic Notation (SAN)
# board.push_san('e4')
# board.push_san('e5')
# board.push_san('Qf3')
# board.push_san('d5')
# board.push_san('Bc4')
# board.push_san('dxe4')
# ------------------------
board.push_san('e4')
board.push_san('e5')
board.push_san('Be2')
board.push_san('Be7')
board.push_san('Nh3')
board.push_san('Nh6')
move = chess.Move.from_uci('e1g1')
if board.is_castling(move):
    board.push(move)
print(board)
print("Checkmate:", board.is_checkmate())