import chess
board = chess.Board()
# Making moves using Standard Algebraic Notation (SAN)
board.push_san('e4')
board.push_san('e5')
board.push_san('Qf3')
board.push_san('d5')
board.push_san('Bc4')
board.push_san('dxe4')
print(board)
print("Checkmate:", board.is_checkmate())