import chess
board = chess.Board()
# Making moves using Standard Algebraic Notation (SAN)
# board.push_san('e4')
# board.push_san('e5')
# board.push_san('Qf3')
# board.push_san('d5')
# board.push_san('Bc4')
# board.push_san('dxe4')
# ------------------------
# board.push_san('e4')
# board.push_san('e5')
# board.push_san('Be2')
# board.push_san('Be7')
# board.push_san('Nh3')
# board.push_san('Nh6')
# move = chess.Move.from_uci('e1g1')
#     board.push(move)
# print(board)
# print("Checkmate:", board.is_checkmate())
# ----------------------------------------------
board.push_san('e4')
board.push_san('e5')
board.push_san('Qh5')
board.push_san('Ke7')
board.push_san('Qxh7')
board.push_san('Ke6')
board.push_san('Qxh8')
board.push_san('Kd6')
board.push_san('Qxg8')
board.push_san('Kc6')
board.push_san('Qxg7')
board.push_san('Kb6')
board.push_san('h4')
board.push_san('Kc6')
board.push_san('h5')
board.push_san('Kb6')
board.push_san('h6')
board.push_san('Kc6')
board.push_san('h7')
board.push_san('Kb6')
board.push_san('h8=Q')
print(board)
print("Checkmate:", board.is_checkmate())